backend:
  name: github
  branch: master # Branch to update (optional; defaults to master)
  repo: suffolklibraries/sljekyll # Path to your Github repository

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News post" # Used in the UI
    folder: "news/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "sidebar-right"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author (e.g. james-powell)", name: "author", widget: "string"}
      - {label: "Publication date", name: "date", widget: "date"}
      - {label: "Category", name: "category", widget: "hidden", default: "news"}
      - {label: "Breadcrumb", name: "breadcrumb", widget: "hidden", default: "news"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "special-events" # Used in routes, e.g., /admin/collections/blog
    label: "Special event" # Used in the UI
    folder: "_events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "name", widget: "string"}
      - {label: "Location key (e.g. stowmarket-library)", name: "location", widget: "string"}
      - {label: "Location text (e.g. Stowmarket Library)", name: "location-text", widget: "string"}
      - {label: "Start date (format YYYY-MM-DD)", name: "event-start-date", required: "false", widget: "string"}
      - {label: "End date  (format YYYY-MM-DD)", name: "event-end-date", required: "false", widget: "string"}
      - {label: "Start time (24h clock, no punctuation)", name: "event-start-time", required: "false", widget: "string"}
      - {label: "End time (24h clock, no punctuation)", name: "event-end-time", required: "false", widget: "string"}
      - {label: "Breadcrumb", name: "breadcrumb", widget: "hidden", default: "y"}
      - {label: "Body", name: "body", widget: "markdown"}
